
# Site settings
title: TKVTV
email: xxx@facebook.com
baseurl: "/page79" # the subpath of your site, e.g. /blog/
url: "https://takagotch.github.io" # the base hostname & protocol for your site

markdown: kramdown
# toc_levels: 1……2

# paginate: 10
# paginate_path: ":num"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - blog pull and debug.bat
  
  
